### ISSUE TITLE
Unnecessary check for management cert when using storage account key

### ISSUE THREAD

**Issue by ffaghri1** [Azure/azure-batch-samples#125]
This check:
`    if args.subscriptionid is not None and args.managementcert is None:
        raise ValueError(
            'cannot specify subscription id without a management cert')`

is unnecessary for the following usage:
`python $blobxfer_location/blobxfer.py --timeout 1800 --numworkers $NUM_WORKERS --subscriptionid $subscriptionid --storageaccountkey $storage_account --download --remoteresource`

**Comment by alfpark** [comment]
A subscriptionid is not needed with storage account key. It should only be specified with a management cert for legacy ASM operation.
