### ISSUE TITLE
4.0 SDK

### ISSUE THREAD

**Issue by sbryfcz** [Azure/azure-batch-samples#127]
It would be awesome to have these updated for the 4.0 SDK. 

Thanks for all your work/help!

**Comment by matthchr** [comment]
Hi @sbryfcz - I'm actually working on this right now and will probably have a PR out later today/tomorrow.

**Comment by sbryfcz** [comment]
Thanks! That's awesome! Can't wait to try them out.

**Comment by matthchr** [comment]
This is fixed by PR #128

**Comment by sbryfcz** [comment]
Works great. Thanks for all your help. 

1 more question I have (and cant find an example). Have you gotten Linux instances running with the .NET code? I've been trying to mashup the Linux python examples with the .NET ones but I keep getting generic errors from .NET. I've been trying to port over the python helper select_latest_verified_vm_image_with_node_agent_sku method but having trouble with that as well.  Any help in this area would be awesome. I can open a new 'issue' if you'd like.

```C#
var imageReference = new ImageReference("UbuntuServer", "Canonical", "14.04.2-LTS", "latest");
var virtualMachineConfiguration = new VirtualMachineConfiguration(imageReference, "Batch.Node.Ubuntu 14.04");

// For this job, ask the Batch service to automatically create a pool of VMs when the job is submitted.
unboundJob.PoolInformation = new PoolInformation()
{
    AutoPoolSpecification = new AutoPoolSpecification()
    {
        AutoPoolIdPrefix = "HelloWorld",
        PoolSpecification = new PoolSpecification()
        {                        
            TargetDedicated = configurationSettings.PoolTargetNodeCount,
            //CloudServiceConfiguration = new CloudServiceConfiguration(configurationSettings.PoolOSFamily),
            VirtualMachineSize = configurationSettings.PoolNodeVirtualMachineSize,      
            VirtualMachineConfiguration = virtualMachineConfiguration                  
        },
        KeepAlive = false,
        PoolLifetimeOption = PoolLifetimeOption.Job
    }
};
```

**Comment by sbryfcz** [comment]
Sorry! Found my issue. Didnt change the VirtualMachineSize to an appropriate choice. 

Thanks again for the help
