### ISSUE TITLE
No statistics for Jobs

### ISSUE THREAD

**Issue by Malondron** [Azure/azure-batch-samples#139]
Hi,
the problems from the closed issue 131 seems to persist. Both using the BatchExplorer and the usual batch rest API, the tasks have statistics, but the jobs don't.

**Comment by paselem** [comment]
Hello,
There are a couple of things at play here which are worth checking out:
1. Make sure that your jobs are recent. The Batch Service addressed a bug where older jobs and pools were not emitting job and pool statistics
2. Job and Pool statistics are a best effort metric and can be expected to take around 45 minutes to be available. Please allow some time for the job statistics to get aggregated.

Please reach out again if you are still unable to get statistics for your job.

**Comment by Malondron** [comment]
Hi,

if the jobs are short (minutes or in any case less than 45 minutes), are there no statistics when they finish then?

**Comment by paselem** [comment]
That is correct. The statistics will still take the same amount of time. Even after the job finishes, it can still take around 45 minutes for the statistics to be available for the job.

**Comment by alfpark** [comment]
Closing as there has been no response and appears to be resolved.
