### ISSUE TITLE
Blobxfer: Storage account key visible in ps

### ISSUE THREAD

**Issue by tinygrasshopper** [Azure/azure-batch-samples#160]
The storage account key is taken in as a command line parameter only for blobxfer. Which implies that the storageaccountkey which is a secret for the account is visible in the ps aux output, for big uploads. This a security issue, other clients(e.g. the aws client for s3) get around this issue by accepting the secrets as a environment variable or a config file. 

Thoughts?

cc @dagrol

**Comment by alfpark** [comment]
Agreed, I'll work on accepting keys via environment variables.

Json file config is in my backlog.

**Comment by alfpark** [comment]
Closing with the addition of credential env var support.  Unsure of timeline for json file config support, but hopefully will be added in a future release.

**Comment by tinygrasshopper** [comment]
Looks great, thanks @alfpark !
