### ISSUE TITLE
Download container example requires --download?

### ISSUE THREAD

**Issue by asw** [Azure/azure-batch-samples#166]
First and foremost, I really like blobxfer. I've only just discovered it but it really hits a sweet spot for a handful of use cases I have right now. I came across a small issue in the README (https://github.com/Azure/azure-batch-samples/blob/master/Python/Storage/README.rst ). 

Should:
    blobxfer mystorageacct container0 mylocaldir --remoteresource .

Be:
   blobxfer mystorageacct container0 mylocaldir --download --remoteresource .

The former wrote various temp files to be container and it ended up being a bit confusing.

**Comment by alfpark** [comment]
@asw As stated in the README:

> If mylocaldir directory exists, the script will attempt to upload the directory instead of downloading it. In this case, if you want to force the download direction, indicate that with --download.

blobtmp files are allocated for file preallocation and to prevent confusion with files that have not been integrity checked.

**Comment by alfpark** [comment]
Thanks for using the tool, closing.

**Comment by asw101** [comment]
Thank you Fred, I'd missed that in the README as my first bite using the tool was in a rush. I see that if I run it once, it will download, and then a subsequent execution of the same command will upload (so I'll force the direction). Thank you for a great tool, glad to have found it!

**Comment by asw** [comment]
Thank you Fred, I'd missed that in the README as my first bite using the tool was in a rush. I see that if I run it once, it will download, and then a subsequent execution of the same command will upload (so I'll force the direction). Thank you for a great tool, glad to have found it!
