### ISSUE TITLE
Problem with BatchServiceClient init on azure==2.0.0rc5

### ISSUE THREAD

**Issue by cameroun** [Azure/azure-batch-samples#169]
I just tried to run the python sample with azure 2.0.0rc5.
I get the following error

> me@camnetwork:/tmp/azure-batch-samples/Python/Batch/article_samples$ python python_tutorial_client.py 
> Sample start: 2016-07-29 12:07:48
> 
> Uploading file /tmp/azure-batch-samples/Python/Batch/article_samples/python_tutorial_task.py to container [application]...
> Uploading file /tmp/azure-batch-samples/Python/Batch/article_samples/data/taskdata1.txt to container [input]...
> Uploading file /tmp/azure-batch-samples/Python/Batch/article_samples/data/taskdata2.txt to container [input]...
> Uploading file /tmp/azure-batch-samples/Python/Batch/article_samples/data/taskdata3.txt to container [input]...
> Traceback (most recent call last):
>   File "python_tutorial_client.py", line 480, in <module>
>     base_url=_BATCH_ACCOUNT_URL)
>   File "/tmp/sandbox/local/lib/python2.7/site-packages/azure/batch/batch_service_client.py", line 137, in __init__
>     self._serialize = Serializer(client_models)
> TypeError: __init__() takes exactly 1 argument (2 given)
>

**Comment by mmacy** [comment]
Hi Cameroun,

This indicates that the `azure-batch` package installed on your machine is not up-to-date, as we did change the signature for the *BatchClient* to take 2 arguments in the latest version. Please check your current version of the package:

`pip show azure-batch`

If version `0.30.0rc5` is not shown, please update to the latest version. You can do so with:

```
pip uninstall azure-batch
pip install --pre azure-batch
```

Thanks for trying out the tutorial!

**Comment by alfpark** [comment]
Closing since it appears the issue has been resolved.
