### ISSUE TITLE
Please publish batchExplorer

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-batch-samples#189]
Please can you provide a Batch Explorer tool for our Operations team to use.

Thanks

**Comment by matthchr** [comment]
Hello @mikeblakeuk - BatchExplorer is provided as a sample of how to write a UI on top of the Azure Batch APIs. It is definitely useful as a debugging tool, but we do not officially publish its binaries. If you want a build of it, you can build it from source quite easily (just open the project in VS and build it).

On the other hand you can also use the [Azure Portal](https://portal.azure.com/) to perform debugging/diagnostic actions on your Batch accounts.

Can you clarify what exactly you're looking for?

Thanks,
-Matt

**Comment by matthchr** [comment]
Closing this as there as been no response
