### ISSUE TITLE
Cannot delete pool in Batch Explorer

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-batch-samples#202]
It seems that Batch Explorer has a bug that when trying to delete a pool nothing happens. A colleague confirmed that. Deleting the pool via Azure Portal works, and also in my own Python code using the azure-batch library.

**Comment by darylmsft** [comment]
So "this works for me" so we need to know more about your experience.  Can we get a bit more context?
Version of Batch Explorer... approximate date that you pulled down the sources/sample.
"button" or "context menu"
where (what pane) is the control that you are using to trigger the delete?

**Comment by matthchr** [comment]
Closing this as there has been no response.

Do note that BatchExplorer is now deprecated in favor of the cross-platform tool [Batch Labs](https://github.com/Azure/BatchLabs).
