### ISSUE TITLE
How to prepare the OpenFOAM tgz files?

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/azure-batch-samples#204]
Could you please provide more information on how to prepare these files?

- wget http://<storage-account>.blob.core.windows.net/<container>/OpenFOAM_CentOS7_HPC.tgz
- wget http://<storage-account>.blob.core.windows.net/<container>/OpenFOAM_CentOS7_HPC_libs.tgz
- wget http://<storage-account>.blob.core.windows.net/<container>/motorBike_3M.tgz
- wget http://<storage-account>.blob.core.windows.net/<container>/ParaView-3.14.1-Linux-64bit.tar.gz

What they actually contain and How did you generate these files?

Is Intel MPI a part of CentOS images? 

Thanks,
lumirosl @ MSFT

**Comment by alfpark** [comment]
@lmiroslaw Please refer to this guide: https://blogs.technet.microsoft.com/windowshpc/2016/07/20/introducing-mpi-support-for-linux-on-azure-batch/

@msoni3 can provide additional info.

**Comment by matthchr** [comment]
Closing this since it seems like it was answered.
