### ISSUE TITLE
v3.0.0 of the Python SDK breaks Python Batch samples

### ISSUE THREAD

**Issue by khilscher** [Azure/azure-batch-samples#222]
The samples and accompanying tutorial at https://docs.microsoft.com/en-us/azure/batch/batch-python-tutorial need to be updated for v3.0.0 of the Azure Batch Client for Python. For example, target_dedicated and current_dedicated on CloudPool, AddPoolParameter and PoolSpecification have been renamed to target_dedicated_nodes and current_dedicated_nodes.

**Comment by annatisch** [comment]
Thanks @khilscher  - just waiting for PR #221 to be merged :)

**Comment by annatisch** [comment]
Merged!

**Comment by khilscher** [comment]
Thanks!
