### ISSUE TITLE
Get Python client SDK version using __version__ 

### ISSUE THREAD

**Issue by khilscher** [Azure/azure-batch-samples#223]
Is there a way to get the ```__version__``` from the Batch Python client lib? e.g. 2.0.1?  If not, it would be helpful to implement ```__version__``` in the Batch Python client lib so calling code can detect and work around SDK changes.

**Comment by annatisch** [comment]
Hi @khilscher,
Yes the ` __version__` attribute is implemented in all modules of the azure SDK:
```
>>> import azure
>>> azure.batch.__version__
'3.0.0'
```

**Comment by khilscher** [comment]
Awesome. Quick correction, on my dev machines I had to use...

```
>>> import azure.batch
>>> azure.batch.__version__
'3.0.0'
```
