### ISSUE TITLE
Need Example for Application Packages

### ISSUE THREAD

**Issue by vejuhust** [Azure/azure-batch-samples#236]
As per [this guide](https://docs.microsoft.com/en-us/azure/batch/batch-application-packages), application **litware** was created as demo/example, can you please release its source code for developers to learn and debug?

**Comment by davidkydd** [comment]
Litware isn't a real program, it was just used as an example application name. Apologies for the confusion.

**Comment by mmacy** [comment]
**Litware** is a fictional software company used by Microsoft in various documentation and example capacities. Other fictional companies are **Contoso** and **Fabrikam**. For more information, please see the following MSDN blog post:

[Why do I see the same fake names in Microsoft samples over and over?](https://blogs.msdn.microsoft.com/oldnewthing/20061013-05/?p=29393)

**Comment by Tatsinnit** [comment]
Thanks guys @mmacy & @davidkydd  for clarifying the background for the name "liteware".
  
Further, I will point few resources which will help.
  
In the official [sample code](https://github.com/Azure/azure-batch-samples) it is easy to add app pkg code if you are familiar with the details mentioned in [application package documentation](https://docs.microsoft.com/en-us/azure/batch/batch-application-packages).  _(please be aware that you have read the whole page carefully as there are few moving parts to the setup)_.

I will emphasize on carefully reading the [documentation](https://docs.microsoft.com/en-us/azure/batch/batch-application-packages), it further carefully details pool level and task level packages, How you setup your packages via portal, and deciding if the design will need application package or any other way.

Few more helpful link:

* Batch app pkg documentation [here ](https://docs.microsoft.com/en-us/azure/batch/batch-application-packages) & some mention [here](https://azure.microsoft.com/en-au/blog/application-packages-and-task-dependencies-now-available-on-azure-batch/). 
* Good [demo to leverage](https://github.com/Azure/azure-batch-samples/tree/master/CSharp)   (I think all you need to do is copy paste the code via this or this link and enable app packages at Pool level **or** Task Level).
* [Detailed Azure batch learning path](https://azure.microsoft.com/en-us/documentation/learning-paths/batch/). 
*  [Social MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurebatch) or [SO](https://stackoverflow.com/questions/tagged/azure-batch) for wider knowledge on in particular in this context this might help.  and in particular this might help [SO link](https://stackoverflow.com/questions/45065950/application-packages-with-vm-configuration/45124459#45124459)

Closing down this issue as it seems like combination of misunderstanding and possible documentation reach.

Thanks heaps.

**Comment by vejuhust** [comment]
@davidkydd @mmacy Thanks for your info! I didn't realize **Litware** is just another **Contoso**.

@Tatsinnit Many thanks to you for this summary! Apart from the application package itself, Azure Batch looks like another Cosmos, and it's been 3 years since Azure Batch GTM. But I still can't find any related books or video courses for developers like me 😢

**Comment by Tatsinnit** [comment]
You are welcome @vejuhust :) ! 

When I started I find document was very easy to follow, it’s just it takes one to sink in the concept because it does few things at once, I will see if I can add some quick YouTube video, (given that it will be helpful but no commitments, so not sure when that will happen :) ) 

:bulb: if you have any code specific questions you can ask in forums or flick me your repo where I can try and help. In one of the stackoverflow links the explaination is from very basics, if you are familiar with rest of the concepts of batch, the msdn blog is really easy to follow and I will encourage you to try it out along with other material I have shared above.

:bulb: You can give it a try to get at least the Azure batch sample project running and then adding app pkgs are mere copy paste of few lines of code if you have set them correctly.

Thanks,

**Comment by vejuhust** [comment]
@Tatsinnit Agree! I dived into the this repo for a few days. And when my own code doesn't work as the doc, I tend to figure out the issue by comparing with the example code. 
If you're gonna make YouTube video, what about creating a Pluralsight course?
Btw, may I have your alias? So I can ping you on Skype if necessary.
