### ISSUE TITLE
System.ArgumentException: 'Primary and secondary location URIs in a StorageUri must point to the same resource. Parameter name: secondaryUri'

### ISSUE THREAD

**Issue by naunihalsidhu** [Azure/azure-batch-samples#237]
Getting the following error with C# Sample in jobs.cs

 CloudStorageAccount cloudStorageAccount = new CloudStorageAccount(
                new StorageCredentials(
                    accountSettings.StorageAccountName,
                    accountSettings.StorageAccountKey),
                accountSettings.StorageServiceUrl,
                useHttps: true);

System.ArgumentException: 'Primary and secondary location URIs in a StorageUri must point to the same resource.
Parameter name: secondaryUri'

**Comment by matthchr** [comment]
Given the lack of response above, closing this. Feel free to reopen if you're still observing this.
