### ISSUE TITLE
Can't get OpenFOAM_CentOS7_HPC.tgz following OpenFoam Build Page instructions

### ISSUE THREAD

**Issue by dedreira** [Azure/azure-batch-samples#248]
Hi! I'm trying to follow the steps of the tutorial 

https://blogs.technet.microsoft.com/windowshpc/2016/07/20/introducing-mpi-support-for-linux-on-azure-batch/

but to prepare these files

- OpenFOAM_CentOS7_HPC.tgz
- OpenFOAM_CentOS7_HPC_libs.tgz

the tutorial redirects to this page
https://www.openfoam.com/code/build-guide.php

and after following the steps provided I didn't find any of the two files.
Maybe the build guide has changed?
I need some help :(
Thanks in advance!

**Comment by alfpark** [comment]
These files are not provided, you have to compile/build them yourself. However, if your scenario is amenable to containers, you can take a look at [Batch Shipyard](https://github.com/Azure/batch-shipyard) and the [OpenFOAM recipe](https://github.com/Azure/batch-shipyard/tree/master/recipes/OpenFOAM-Infiniband-IntelMPI).
