### ISSUE TITLE
AttributeError: 'module' object has no attribute '_parse_blob_enum_results_list'

### ISSUE THREAD

**Issue by johnarnold** [Azure/azure-batch-samples#37]
Receiving error when transferring blob:

Traceback (most recent call last):
  File "blobxfer.py", line 1310, in <module>
    main()
  File "blobxfer.py", line 980, in main
    blobskipdict = get_blob_listing(blob_service, args)
  File "blobxfer.py", line 664, in get_blob_listing
    maxresults=_MAX_LISTBLOBS_RESULTS)
  File "blobxfer.py", line 547, in azure_request
    raise exc
AttributeError: 'module' object has no attribute '_parse_blob_enum_results_list'

This problem starting coincides with the latest release of the Azure SDK for Python (1.0) and the problem goes away when rolling back to 0.11.1 version.

Look at:
https://github.com/Azure/azure-storage-python/releases

Interesting that the namespace has changed from azure.storage to azure.storage.blob -- could just be that?

Thanks,
John

**Comment by alfpark** [comment]
PR #42 fixes this issue and removes dependency on azure packages for pure sas mode operation.
