### ISSUE TITLE
Upload fails when the container doesn't exist

### ISSUE THREAD

**Issue by paulo-santos** [Azure/azure-batch-samples#70]
**create container** and **skip on MD5 match** are both True by default.
So, when running a command like:
```
blobxfer storage_account new_container /path/to/dir --upload --storageaccountkey=${AZURE_STORAGE_ACCOUNT_KEY} 
```
the upload fails because the script, first tries to retrieve the blob listings from the container. But it will raise an azure.common.AzureMissingResourceHttpError and stop the execution.

**Comment by alfpark** [comment]
Thanks for reporting the issue. I'll create a fix for the issue.
