### ISSUE TITLE
Bug When Uploading

### ISSUE THREAD

**Issue by theodorDiaconu** [Azure/azure-batch-samples#83]
Time:2015-11-17T07:44:37.7457230Z</Message></Error>
The specified blob or block content is invalid.
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobOrBlock</Code><Message>The specified blob or block content is invalid.
RequestId:445ea4c3-0001-00ed-330b-217d34000000
Time:2015-11-17T07:44:32.1473355Z</Message></Error>

**Comment by alfpark** [comment]
See #43.

**Comment by alfpark** [comment]
Please take the corrective actions noted in that issue. Closing.

**Comment by theodorDiaconu** [comment]
@alfpark I did! I read it before I opened this ticket. It had absolutely no effect, I have now started logging for azure, to see maybe they give me a hint.
