### ISSUE TITLE
Select the start point of the path when --keeprootdir is enabled

### ISSUE THREAD

**Issue by jmlero** [Azure/azure-batch-samples#87]
Hi,

Maybe I'm wrong but I think that makes no difference when the option --keeprootdir is enabled or not.

I am using a modified version of blobxfer, in my version I can select with a number the start point of the local path in order to create the virtual path on azure.

Example:

/home/user/azure/ folder1
                             folder2/subfolder1

With my version, selecting 3 as start point, I can create the following virtual path on azure:

https://xxx.blob.core.windows.net/container/folder1
https://xxx.blob.core.windows.net/container/folder2/subfolder1

Instead of:

https://xxx.blob.core.windows.net/container/home/user/azure/folder1
https://xxx.blob.core.windows.net/container/home/user/azure/folder2/subfolder1

I can pull a request and add this option to the flag --keeprootdir like:
--keeprootdir \[STARTPOINT\] (with 1 as default)

Regards,

**Comment by alfpark** [comment]
It does make a difference. If I upload with the flag on, it will preserve the localresource root directory. Or if the flag is not specified, that directory is removed.

I will consider replacing this flag with a component strip.

Also, as a request: We have gotten messages inquiring if your repository holds the "next version" of blobxfer. It clearly does not - would you mind changing your script to not be called blobxfer_v2? Additionally, it is misleading to users to wrap blobxfer and call it AzCopy unless your project intends to match full parity and breadth of the Windows AzCopy (which is much more comprehensive against Azure Storage supporting all storage object types).

**Comment by jmlero** [comment]
Hi,

Thanks for kindly consider my request, I am not sure if my previous explanation was clear enough, but my suggestion was just add something like the flag --strip-components of tar for keeprootdir. and modifying the line 988 and rtmp.

Also, I deleted my file blobxfer_v2, was not my intention to make a confusion or a misleading the use of the concept Windows AzCopy.

PS: blobxfer, with some additional features, is really useful for me, but since the project was hold for many time and the name is "azure-batch-samples" including another C# project, I was not sure about the continuity of this project.

**Comment by alfpark** [comment]
@jmlero 

Thanks for clarifying your project position. Blobxfer will be supported by the Azure Batch/HPC team for the foreseeable future as it supports use cases within our products and services. We will clearly state if this is not the case, as many individuals and organizations have included blobxfer in their workflows.

**Comment by jmlero** [comment]
OK, thanks. Sorry for the offtopic, in this case, if someone needs a new feature related to blobxfer, what should be the action or the steps?
First open an issue asking for the feature?

**Comment by alfpark** [comment]
@jmlero 

Correct, just open up an issue asking for the feature.
