### ISSUE TITLE
Max retries exceeded with url error

### ISSUE THREAD

**Issue by sidcarter** [Azure/azure-batch-samples#93]
After downloading the latest fix for the issue that was recently closed with #82, I ran into another issue:

```
HTTPSConnectionPool(host='sampleblobstore.blob.core.windows.net', port=443): 
Max retries exceeded with url: /xxxxxxxxxxxxuyaidlajdsflaksfcc0dc9fe4-671141903_p.jpg?blockid=MDAwMDAwMDA=&comp=block 
(Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x44834850>: 
Failed to establish a new connection: [Errno -2] Name or service not known',))
```

This is a largish folder that I've been trying to upload to Azure. All the other smaller folders were uploaded fine.

My command I used:

```
blobxfer.py --storageaccountkey $AZURE_STORAGE_ACCESS_KEY $AZURE_STORAGE_ACCOUNT $AZURE_CONTAINER_NAME .
```

**Comment by alfpark** [comment]
Please retry `--numworkers` set to a lower value than the default on your machine. Start with a low number, say in the range of 4-8. Then modify to larger numbers with regard to your network connection conditions.
